name: Download and Upload Kernel Assets

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      # 固定最新6.12 GKI SHA1
      KERNEL_COMMIT: f01d585ebe1567ed9d53f4de4d703a481dd9e199
      RELEASE_TAG: gki-6.12-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y aria2 gh

      - name: Download GKI Kernel Source
        run: |
          KERNEL_URL="https://android.googlesource.com/kernel/common/+archive/${{ env.KERNEL_COMMIT }}.tar.gz"
          KERNEL_FILE="gki-6.12-${{ env.KERNEL_COMMIT }}.tar.gz"
          
          echo "Start download commit: ${{ env.KERNEL_COMMIT }}"
          aria2c -s16 -x16 -k1M --file-allocation=none "$KERNEL_URL" -o "$KERNEL_FILE"
          
          ls -lh "$KERNEL_FILE"

      - name: Create & Upload Release
        run: |
          gh release view ${{ env.RELEASE_TAG }} &>/dev/null || \
          gh release create ${{ env.RELEASE_TAG }} \
            --title "GKI 6.12 Latest Source Archive" \
            --notes "Auto upload android16-6.12-2025-06_r58 source code\nCommit: ${{ env.KERNEL_COMMIT }}"
          
          gh release upload ${{ env.RELEASE_TAG }} gki-6.12-${{ env.KERNEL_COMMIT }}.tar.gz --clobber
